### ISSUE TITLE
Error while setup 

### ISSUE THREAD

**Issue by heaven00** [cbgaindia/union-budget-board#10]
`ImportError: No module named djangocms_text_ckeditor`
Is there something else to run with a fresh installation ? @akshay2905 

Full traceback 
```
Traceback (most recent call last):
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/jayant/envs/django_cms_cbga/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/jayant/anaconda3/envs/py27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named djangocms_text_ckeditor

```

**Comment by imakshayverma** [comment]
@heaven00 This error pops up after which step?

**Comment by heaven00** [comment]
While running `python manage.py runserver`

**Comment by imakshayverma** [comment]
Looks like djangoCMS isn't installed yet. 

If you have used django CMS installer, the packages are installed in the environment once you create a project. by using the following command: `djangocms -f -p . projectname`. 

One not so good hack would be to create a test project and perhaps delete it then. This would install the basic packages of django-cms and django. 

Another option is to install it manually. Please refer this link - [Install Manually](http://docs.django-cms.org/en/release-3.4.x/how_to/install.html#install-the-django-cms-package)

**Comment by heaven00** [comment]
The instructions says not to do make project. 
we would need better then the hack

**Comment by heaven00** [comment]
okay, figured it out all the requirements are already mentioned in the `requirement.txt`

so the instructions for installation should be : -

```
pip install -r requirements.txt
python manage.py migrate
python manage.py runserver
```
